# Generated by Django 4.2.3 on 2023-07-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='header',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
