# Generated by Django 4.2.3 on 2023-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_header_details_alter_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200, unique=True)),
                ('played', models.IntegerField()),
                ('goal_diff', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
