# Generated by Django 4.2.3 on 2023-07-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='goal_diff',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='table',
            name='played',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='table',
            name='points',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='table',
            name='team',
            field=models.CharField(max_length=200),
        ),
    ]
