# Generated by Django 4.2.3 on 2023-07-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.CharField(max_length=200)),
                ('assists', models.CharField(max_length=200)),
                ('goals_assits', models.CharField(max_length=200)),
                ('penalty_goals', models.CharField(max_length=200)),
                ('freekick_goals', models.CharField(max_length=200)),
                ('yellow_cards', models.CharField(max_length=200)),
                ('red_cars', models.CharField(max_length=200)),
                ('penalties_won', models.CharField(max_length=200)),
                ('chances_created', models.CharField(max_length=200)),
                ('chances_misseds', models.CharField(max_length=200)),
                ('acc_pass_per_g', models.CharField(max_length=200)),
                ('succ_dribbles', models.CharField(max_length=200)),
                ('clearances', models.CharField(max_length=200)),
                ('clean_sheet', models.CharField(max_length=200)),
            ],
        ),
    ]
