# Generated by Django 4.2.3 on 2023-07-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_statistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='chances_misseds',
            new_name='chances_missed',
        ),
    ]
